version: '3.9'

services:

  postgres:
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - src/.env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U mari
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - backend_nw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - src/.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge
